databases:
  - name: quiz
    databaseName: quiz
    user: quiz

services:
  - type: web
    name: quiz
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn quiz.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: quiz
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4