# Generated by Django 4.1.7 on 2023-04-05 20:55

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('question', models.CharField(max_length=255)),
                ('answer', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='QuizUserAnswerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('question', models.CharField(max_length=255)),
                ('answer', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), size=None)),
                ('user_answer', models.IntegerField()),
                ('is_posted', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
